### ISSUE TITLE
[0.6.1] Error parsing data.xml based on generated template

### ISSUE THREAD

**Issue by OhiraKyou** [pixelnest/presskit.html#3]
I'm using version 0.6.1 on Windows 10 64-bit, installed from Node.js.

My data.xml is based on the new company command's generated template. And, according to [the recommended validator](https://codebeautify.org/xmlvalidator), it is valid. Yet, I'm seeing the following error on build:
```
Finding data…
There was an error during the parsing of `C:\presskitsource\data.xml`. Check that your XML document is valid.
```
Here's [a zip file containing two data.xml that I tried](https://github.com/pixelnest/presskit.html/files/1311600/presskit.parsing.error.source.zip) (one full, and one trimmed).

**Comment by solarsailer** [comment]
Hello,

Indeed, it looks like there's an error with a recent version of node and one of the package we use.

I will publish a fix soon.

Thanks. :)

**Comment by OhiraKyou** [comment]
While trying to find a workaround from my end, I tried these Node.js versions:
6.11.3
7.10.1
8.1.4
8.4.0

I also tried these presskit versions:
0.6.1
0.6.0
0.5.0

Same error in all cases.

**Comment by solarsailer** [comment]
`0.6.2` has been published. Re-open this issue if the problem is still here. ;)
